export const personMap: Record<string, string> = {
  dybbber: "martin dybdal",
  "mighty munter": "munter",
  boelling: "bo elling",
  boælling: "bo elling",
  "bo ælling": "bo elling",
  fairchil: "fairchild",
  "harlems hårde hurlumhejsere": "harlem klub",
  "jakob uhd af revyen": "jakob uhd",
  "jakob uhd jepsen": "jakob uhd",
  uhd: "jakob uhd",
  jenny: "jenny-margrethe vej",
  "katrine hommelhof": "katrine hommelhof jensen",
  madssß: "mads sejersen",
  madß: "mads sejersen",
  madss: "mads sejersen",
  "mad\\ss": "mads sejersen",
  msiebuhr: "morten siebuhr",
  siebuhr: "morten siebuhr",
  sandfeld: "allan sandfeld jensen",
  // allan: "allan sandfeld jensen",
  allans: "allan sandfeld jensen",

  "søren tm": "søren trautner madsen",
  "søren trautner": "søren trautner madsen",
  "søren trauntner madsen": "søren trautner madsen",
  trauma: "søren trautner madsen",
  "søren (\\texttt{trauma})": "søren trautner madsen",
  "søren (\\texttt{trauma}) -- det er deres skuld det hele":
    "søren trautner madsen",

  adhh: "adam hasselbalch hansen",
  adam: "adam hasselbalch hansen",

  buzz: "niels bosworth",
  buzzword: "niels bosworth",
  "niels buzz-worth": "niels bosworth",
  uffe: "uffe gram christensen",
  "uffe c": "uffe gram christensen",
  "uffe chistensen": "uffe gram christensen",
  "uffe christensen": "uffe gram christensen",
  uffec: "uffe gram christensen",
  "neger-uffe": "uffe gram christensen",

  "uffe friis": "uffe friis lichtenberg",
  "uffe fl": "uffe friis lichtenberg",
  uffefl: "uffe friis lichtenberg",
  ulla: "uffe friis lichtenberg",
  "ulla tordenskjold": "uffe friis lichtenberg",
  uphphefl: "uffe friis lichtenberg",
  "{\\tt uffefl}": "uffe friis lichtenberg",

  "katrine h": "katrine hommelhoff jensen",
  "katerine hommelhof jensen": "katrine hommelhoff jensen",
};
